services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: idoD3011!
      MYSQL_DATABASE: lesson_service_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      RUNNING_IN_DOCKER: true
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/personal_commitment
      MONGO_URI_PROD: mongodb+srv://user:pass@cluster.mongodb.net/prod_db
      JWT_SECRET: your_jwt_secret
      JWT_REFRESH_SECRET: your_jwt_refresh_secret
      MAILTRAP_HOST: sandbox.smtp.mailtrap.io
      MAILTRAP_PORT: 25
      MAILTRAP_USER: 635b669cb82c63
      MAILTRAP_PASS: 0aa95399e77813
      ACCESS_TOKEN_EXPIRY: 7d
      REFRESH_TOKEN_EXPIRY: 7d
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: lesson.events
      BREVO_HOST: smtp-relay.brevo.com
      BREVO_PORT: 587
      BREVO_USER: 8bf827001@smtp-brevo.com
      BREVO_PASS: O9N5y4sU7023L6xd
      BREVO_SENDER: tutorpro2026@gmail.com
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq

  lesson-service:
    build: ./lesson-service
    container_name: lesson-service
    environment:
      RUNNING_IN_DOCKER: true
      NODE_ENV: development
      SERVER_PORT: 3002
      DB_NAME: lesson_service_db
      DB_USER: root
      DB_PASSWORD: idoD3011!
      DB_HOST: mysql
      DB_PORT: 3306
      JWT_SECRET: your_jwt_secret
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: lesson.events
    ports:
      - "3002:3002"
    depends_on:
      - mysql
      - rabbitmq

  report-service:
    build: ./reporting-service
    container_name: reporting-service
    environment:
      RUNNING_IN_DOCKER: true
      PORT: 3003
      MONGO_URI: mongodb://mongo:27017/reportsDB
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: lesson.events
      QUEUE_REPORTS: reports.queue
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      RUNNING_IN_DOCKER: true
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001/auth
      LESSON_SERVICE_URL: http://lesson-service:3002/lessons
      REPORT_SERVICE_URL: http://reporting-service:3003/reports
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - lesson-service
      - report-service

volumes:
  mysql_data:
  mongo_data:
